# Generated by Django 4.2.16 on 2024-10-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finder_no',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
