# Generated by Django 4.2.16 on 2024-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0003_alter_product_finder_no_alter_product_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='finder_email',
            field=models.EmailField(max_length=254),
        ),
    ]
