# Generated by Django 4.2.16 on 2024-10-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostandfound', '0004_alter_product_finder_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Kangaru', max_length=100),
            preserve_default=False,
        ),
    ]
